### ISSUE TITLE
Qu32 error message

### ISSUE THREAD

**Issue by lpcollier** [bitfocus/companion-module-allenheath-qu#6]
Thanks for putting this module together. With my Qu32 it's working fine in Qu16 mode, but only controlling 16 channels. When I change to Qu32 (or Qu24) mode I get the error:

`instance(QU): Error updating instance configuration: Cannot read property '0' of undefined`

I'm using buid 3138 on Win64

**Comment by maxks** [comment]
Hi Ipcollier, there was a bug on actions config for QU24/32 console, just fixed and sent for new release.

**Comment by lpcollier** [comment]
Fantastic, thanks, as soon as it's in the beta release I'll test it and let you know. I'm busy integrating a Qu32 into a streaming studio, so if you want any features testing please let me know. Thanks for the module, really useful.

**Comment by maxks** [comment]
It is under construction (3141). I developed this module with QU16 so all specific functions for QU24 / 32, such as matrix or groups, has not been tested. If you'd like to help me you are welcome! Thanks
