### ISSUE TITLE
Fader Level issue

### ISSUE THREAD

**Issue by jan9451803** [bitfocus/companion-module-allenheath-qu#9]
I set the button "A" for Input 1 "Step Fader -1 dB"
and set another buttom "B" let Input 1 go to -17 dB
When Fader Level start at -17 db
I tap "A" button 10 times to -27 dB , and tap "B" button go back to -17 dB
it will be useful.
but, if i tap  A button again, it will beginng in -27 dB to -28 dB
I think this is the problem.

sorry, my english is not very well

**Comment by maxks** [comment]
Thanks for feedbacks. I'll check the issue then I'll reply when it is done.
